export const modalStyle = {
  position: "absolute" as "absolute",
  boxSizing: "content-box",
  display: "flex",
  gap: "10px",
  alignItems: "center ",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  width: 300,
  height: "100px",
  bgcolor: "background.paper",
  boxShadow: 24,
  pl: "30px",
};
